name: Core Deployment

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Version Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
          - prepatch
          - preminor
          - premajor
          - prerelease
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: cnstr/core
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: cnstr-core-buildx-${{ github.sha }}
          restore-keys: |
            cnstr-core-buildx-

      - name: Configure Rust and Cargo
        uses: dtolnay/rust-toolchain@stable

      - name: Configure Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure PNPM and install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--frozen-lockfile]

      - name: Configure Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          platforms: linux/amd64

      - name: Login to tale.me
        uses: docker/login-action@v2
        with:
          registry: tale.me
          username: bot-github
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Update npm versions and set build-time variables
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          pnpm np --no-cleanup --no-tests --no-publish --no-release-draft --yolo --message 'chore: v%s' $BUMP_TYPE
          echo "git_version=$(jq -r '.version' package.json)" >> $GITHUB_ENV
          echo "git_state=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "build_date=$(date --rfc-3339=date)" >> $GITHUB_ENV
        env:
          BUMP_TYPE: ${{ inputs.bump_type }}

      - name: Configure Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build tale.me/canister/core
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tale.me/canister/core:${{ env.git_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-to,mode=max
          build-args: |
            BUILD_DATE=${{ env.build_date }}
            VERSION=${{ env.git_version }}
            GIT_STATE=${{ env.git_state }}

      - name: Update Caching Layers
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-to /tmp/.buildx-cache
